### ISSUE TITLE
Documentation checklist

### ISSUE THREAD

**Issue by edumaciel10** [Open-Pix/ruby-sdk#22]
- [x] Getting Started
- [x] How to create charges
- [x] How to create customers
- [x] How to create webhooks etc.
- [x] How to authenticate
- [x] How to trait errors
- [x] How to test the sdk
- [x] Examples o code

**Comment by erick-tmr** [comment]
https://developers.openpix.com.br/docs/category/ruby
